.\" Manpage for psedit.
.\" Contact psimonson1988@gmail.com to correct errors or typos.
.TH man 1 "06 Jun 2021" "1.0" "psedit man page"
.SH NAME
psedit \- Simple ncurses text editor written in C.
.SH SYNOPSIS
psedit <filename>
.SH DESCRIPTION
psedit is a simple ncurses based text editor capable of basic text editing.
.SH OPTIONS
psedit does not have any options.
.SH SEE ALSO
Nothing
.SH BUGS
No known bugs.
.SH AUTHOR
Philip R. Simonson (psimonson1988@gmail.com)
